[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200


## This rule redirects to an external API, signing requests with a secret

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"